# Generated by Django 5.2 on 2025-09-26 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='api_message_session_45845d_idx',
            old_name='api_messag_session_1c3c1e_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='api_message_role_c2b8f4_idx',
            old_name='api_message_role_idx',
        ),
        migrations.RenameIndex(
            model_name='runlog',
            new_name='api_runlog_session_b769e8_idx',
            old_name='api_runlog_session_status_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent emitting the message (if role=agent/tool)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='api.agentprofile'),
        ),
    ]
